# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A11ysentry < Formula
  desc "Universal multi-platform accessibility engine with TUI and MCP support."
  homepage "https://github.com/mbiondo/a11ysentry"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mbiondo/a11ysentry/releases/download/v0.0.9/a11ysentry_darwin_amd64.tar.gz"
      sha256 "c4226d21896751504b22ae0a13cdeb50e93d48dc26595a79092ddbb3ed4ee811"

      define_method(:install) do
        bin.install "a11ysentry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mbiondo/a11ysentry/releases/download/v0.0.9/a11ysentry_darwin_arm64.tar.gz"
      sha256 "823e343b69ad9b2d55092071bcbdb368ef067450f9d14664da3575e1cd04e76a"

      define_method(:install) do
        bin.install "a11ysentry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mbiondo/a11ysentry/releases/download/v0.0.9/a11ysentry_linux_amd64.tar.gz"
      sha256 "f99c9c50907e74f322fa0783661f421cf4d128aac76c52f29c7f23284936990e"
      define_method(:install) do
        bin.install "a11ysentry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mbiondo/a11ysentry/releases/download/v0.0.9/a11ysentry_linux_arm64.tar.gz"
      sha256 "12188b34c832bdcd956353ec420aff2c2e38df7901099bd590acb94907c6159d"
      define_method(:install) do
        bin.install "a11ysentry"
      end
    end
  end
end
